CREATE SCHEMA IF NOT EXISTS shop;

CREATE TABLE IF NOT EXISTS shop.products (
--    identifier SERIAL PRIMARY KEY,
    identifier BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL
);