DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
--	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, --С 10 версии postgresql
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(60) NOT NULL
);
